# Generated by Django 2.2.1 on 2019-05-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_basecontentother_orderedcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseContentother',
        ),
        migrations.DeleteModel(
            name='OrderedContent',
        ),
    ]
