# Generated by Django 2.2.1 on 2019-05-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190521_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textcontent',
            name='basecontent_ptr',
        ),
        migrations.DeleteModel(
            name='BaseContent',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
    ]
